language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
install:
  - TERM=dumb ./gradlew assemble
script:
  - TERM=dumb ./gradlew check
matrix:
  allow_failures:
    - jdk: oraclejdk8
